### ISSUE TITLE
Morning Session: peer-to-peer code review

### ISSUE THREAD

**Issue by zainsadaqat** [zainsadaqat/leaderboard#7]

**Comment by notlfish** [comment]
Nice job!
I didn't know about the template tag, it's a very interesting HTML feature!

**Comment by rotimiazeez** [comment]
![](https://media.giphy.com/media/cEODGfeOYMRxK/giphy.gif?cid=ecf05e47guzcwu7m88wlv9ify1ekhfe94t66ni4gns3mmog9&rid=giphy.gif&ct=g)
